fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    mysql: "git@github.com:puppetlabs/puppetlabs-mysql.git"
    cron: "git@github.com:roman-mueller/rmueller-cron.git"
  symlinks:
    cacti: "#{source_dir}"
