fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    mysql:
      repo: "https://github.com/puppetlabs/puppetlabs-mysql.git"
      ref: "fa66b38b588"
    cron: "https://github.com/roman-mueller/rmueller-cron.git"
  symlinks:
    cacti: "#{source_dir}"
